name: Build and publish binary wheels.

on:
  workflow_dispatch:

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - name: windows-msvc
            os: windows-latest
            archs: AMD64
            cxx: cl
            cc: cl
            msvc: 1
            environment_script: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat"

          - name: ubuntu-gcc
            os: ubuntu-latest
            archs: x86_64
            cxx: g++
            cc: gcc

          - name: macos-gcc
            os: macos-latest
            archs: x86_64
            cxx: g++
            cc: gcc

    name: Build for ${{ matrix.target.name }} platform.
    runs-on: ${{ matrix.target.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3

    - name: Build binary wheels
      uses: pypa/cibuildwheel@v2.12.0
      env:
        CIBW_ARCHS: >-
          ${{ matrix.target.archs }}
        CIBW_PROJECT_REQUIRES_PYTHON: >-
          >=3.8
        CIBW_BEFORE_ALL: >-
          cmake -DTEST_OPENMP=OFF -DBUILD_INTERFACE_PYTHON=OFF -DBUILD_EXAMPLES=OFF -S . -B build &&
          cmake --build build --config Release --clean-first --target nomadStatic --parallel 2
        CIBW_BEFORE_BUILD: >-
          pip install cython setuptools
        CIBW_ENVIRONMENT: >-
          CC=${{ matrix.target.cc }}
          CXX=${{ matrix.target.cxx }}
          NOMAD_SRC=../../src
          NOMAD_BUILD_DIR=../../build
          NOMAD_MSVC_FLAG=${{ matrix.target.msvc }}
          NOMAD_MSVC_CONF=Release
        CIBW_BUILD_VERBOSITY: >-
          3
      with:
        output-dir: wheelhouse
        package-dir: interfaces/PyNomad

    - name: Collect wheels
      uses: actions/upload-artifact@v3
      with:
        path: wheelhouse/*.whl

  publish:
    name: Publish to PyPi
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Collect wheels (artifacts)
      uses: actions/download-artifact@v3
      with:
        name: artifact
        path: wheelhouse

    - name: Publish wheels to PyPi (testing)
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository_url: https://test.pypi.org/legacy/
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: wheelhouse
        skip_existing: true


